# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac79eac92e74eee6c46772b15b5f30a529b0f58c8ec620ff7e9b693260f94f1c376a0ea50405bd833d4ba7e0c44ed46cfbf2798043a95a0ff227235d4e6bb808

test:
  secret_key_base: 2421a40771f31db53a41cf3485a9a33a6ce5789e7cf75818f85b11e1c250c74afb03349413f86d6bdb4a762d05ecbdb4c47d60ab8afc4f4713d462b9f29306de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
